name: Go CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**.md'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup go
        uses: actions/setup-go@v3.5.0
        with:
          go-version: '^1.18'

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup golangci-lint
        uses: golangci/golangci-lint-action@v3.3.1
        with:
          version: v1.50

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3.5.0
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...
    
    - name: Test
      run: go test -v ./...